name: Epic issue
description: Use this template to track epic issues
title: "[Epic]: "
labels: ["epic", "workflow"]
body:
  - type: markdown
    attributes:
      value: |
        Please give a description for your epic.

